language: node_js
node_js:
  - 7
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd EyeSpy
  - npm install --dev
script:
  - npm run test
  # Disable email notifications
notifications:  
email: false